setup_canopy_env() {
  CANOPY_STORE="$(cd "$BATS_TEST_DIRNAME/.." && pwd)"
  CANOPY_CONFIG="$BATS_TEST_TMPDIR/config"
  CANOPY_STATE="$BATS_TEST_TMPDIR/state"
  CANOPY_RUNTIME="$BATS_TEST_TMPDIR/run"
  export CANOPY_STORE CANOPY_CONFIG CANOPY_STATE CANOPY_RUNTIME
  mkdir -p "$CANOPY_CONFIG" "$CANOPY_STATE" "$CANOPY_RUNTIME"
  PATH="$CANOPY_STORE/bin:$PATH"; export PATH
}
